import { type NextPage } from "next";
import Head from "next/head";
import DefaultLayout from "../components/layout/default";
import AdministrativeAssistance from "../components/sections/administrative";
import BusinessTrands from "../components/sections/business-trands";
import HeroSection from "../components/sections/hero-section";
import Testimonials from "../components/sections/testimonials";
import VirtualAssistance from "../components/sections/virtual-assistance";

const Home: NextPage = () => {
  return (
    <DefaultLayout>
      <Head>
        <title>LUCAS: HOME PAGE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <BusinessTrands />
      <VirtualAssistance />
      <AdministrativeAssistance />
      <Testimonials />
    </DefaultLayout>
  );
};

export default Home;
